export const dashboardData = {
	stats: {
		totalUsers: 10248,
		activeUsers: 8932,
		totalChildren: 12456,
		monthlyGrowth: 12.5,
		systemHealth: 99.9,
		dailyReports: 1834,
	},
	recentUsers: [
		{
			id: 1,
			name: "Sarah Johnson",
			email: "sarah@email.com",
			children: 2,
			joinDate: "2025-01-05",
			status: "active",
		},
		{
			id: 2,
			name: "Michael Chen",
			email: "michael@email.com",
			children: 1,
			joinDate: "2025-01-04",
			status: "active",
		},
		{
			id: 3,
			name: "Emma Wilson",
			email: "emma@email.com",
			children: 3,
			joinDate: "2025-01-03",
			status: "pending",
		},
		{
			id: 4,
			name: "David Brown",
			email: "david@email.com",
			children: 1,
			joinDate: "2025-01-02",
			status: "active",
		},
		{
			id: 5,
			name: "Lisa Garcia",
			email: "lisa@email.com",
			children: 2,
			joinDate: "2025-01-01",
			status: "inactive",
		},
	],
	activities: [
		{
			id: 1,
			type: "user_signup",
			message: "New user registered: Sarah Johnson",
			time: "2 minutes ago",
		},
		{
			id: 2,
			type: "milestone_added",
			message: "Milestone achieved by child Emma Chen",
			time: "15 minutes ago",
		},
		{
			id: 3,
			type: "consultation_booked",
			message: "Consultation booked with Dr. Smith",
			time: "1 hour ago",
		},
		{
			id: 4,
			type: "system_update",
			message: "System maintenance completed",
			time: "3 hours ago",
		},
		{
			id: 5,
			type: "report_generated",
			message: "Monthly report generated",
			time: "5 hours ago",
		},
	],
};
